### ISSUE TITLE
Test stability of the reconstruction 

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/student_project_python_bindings#3]
I saw some strange behavior when running the CUDA implementation on image `a.png`. The object itself was good reconstructed but the orientation or if it was mirrored was constantly changing with each execution.

Please write a helper script that allows to run the Python and CUDA implementation of the algorithm n times on an image. The results should be written to files. This is to verify that the algorithm is generally stable. The possible parameters of the script should be: path to the image file, number of iterations of the whole algorithm, number of iterations within the algorithm.

I would suggest [argparse](https://docs.python.org/3/howto/argparse.html) to handle the arguments in the helper script.

For this issue, issue #1 and #2 should be solved before.

**Comment by afif-ishamsyah** [comment]
what is the best way to write the arrays into images in C++ that works on both linux and windows?

**Comment by SimeonEhrig** [comment]
I would suggest, you solve at first issue #1 With this knowledge, you can safe use the Python library to generate the image. But if you really want to use a C++ solution, I would suggest [pngwriter](https://github.com/pngwriter/pngwriter).

**Comment by afif-ishamsyah** [comment]
So issue #1 is still unsolved?

**Comment by SimeonEhrig** [comment]
I didn't saw your last commit. GitHub does not notify me, if you do a simple commit. Please write a comment in the related issue (in the best case with linkage to the commit, code line or so one) if your are finish and I should review.

I think in the next VC, we change the your workflow to a Pull Request approach. That's makes much easier for me to review and it is really common in open source development.

**Comment by SimeonEhrig** [comment]
But back to the topic, the vector copy example looks good. I think you can use the Python library to write the images. I will do the full review probably tomorrow.

**Comment by SimeonEhrig** [comment]
It's okay, if you only prints the actual reconstructed images without axis, comparison and so one. The following script should do this:

```Python
import imageio
import matplotlib.pyplot as plt
import numpy as np

def main():
    file_names = ["a", "b", "c" ,"d"]
    file_extension = ".png"

    for file_name in file_names:
        image = imageio.imread(file_name + file_extension , as_gray=True)

        plt.imsave(file_name + "_new" + file_extension, image, cmap='gray')

if __name__ == "__main__":
    main()
```

**Comment by afif-ishamsyah** [comment]
It is not that part that I have difficulties. It is how do I get the image from phase retrieval to python with loop

**Comment by afif-ishamsyah** [comment]
@SimeonEhrig could you explain it again what needs to be done with this issue?

**Comment by SimeonEhrig** [comment]
The idea is as test, which do the same like `python example.py` but do this n times and write the result images to files. I'm not sure, if it is necessary any more. The original idea was, to check if the Python implementation and the CUDA implementation are equals over a series of different initial phases. But now, I think we can say that it is.

**Comment by afif-ishamsyah** [comment]
I think I can do the argparse part. Should I do it in example.py?

**Comment by SimeonEhrig** [comment]
No, makes a extra file. The `example.py` should not become to complex.

**Comment by SimeonEhrig** [comment]
The algorithm is already stable. No addition tests are necessary.
